map $http_user_agent $gdox_download_path {
    default /download/;
    ~*Android /download/android/;
    ~*(iPhone|iPad|iPod|CrOS) /download/;
    ~*Windows /download/windows/;
    ~*Macintosh /download/macos/;
    ~*(SteamOS|SteamDeck|Linux|X11) /download/linux/;
}
