#!/bin/sh
set -eu

xemu_root=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
xemu_libraries="${xemu_root}/AppDir/usr/lib"
if [ -n "${LD_LIBRARY_PATH:-}" ]; then
    export LD_LIBRARY_PATH="${xemu_libraries}:${LD_LIBRARY_PATH}"
else
    export LD_LIBRARY_PATH="${xemu_libraries}"
fi
exec "${xemu_root}/AppDir/AppRun" "$@"
