/* Generated by scripts/generate_xenia_policy.py. Do not edit. */
#include "gdox/xenia_policy.h"

#include <string.h>

typedef struct gdox_xenia_title_policy_entry {
    gdox_xenia_title_identity identity;
    gdox_xenia_launch_policy policy;
} gdox_xenia_title_policy_entry;

static const gdox_xenia_runtime runtimes[] = {
    {
        "72ce13097",
#if defined(GDOX_XENIA_CATALOG_WINDOWS)
        "xenia_canary.exe",
        "cbaeb15d890ba7bcc6d8140041bb29c6df3a47f339729ab975bcb3fd633930a5",
        UINT64_C(15783936),
        GDOX_XENIA_GPU_D3D12,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
#elif defined(GDOX_XENIA_CATALOG_LINUX)
        "xenia_canary.exe",
        "cbaeb15d890ba7bcc6d8140041bb29c6df3a47f339729ab975bcb3fd633930a5",
        UINT64_C(15783936),
        GDOX_XENIA_GPU_D3D12,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
#else
        "",
        "",
        UINT64_C(0),
        GDOX_XENIA_GPU_D3D12,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
#endif
    },
    {
        "7d8be7f17",
#if defined(GDOX_XENIA_CATALOG_WINDOWS)
        "xenia_canary.exe",
        "cd0a9c6bddf0d0b960cb24f63efa5d56ecd34fdf20a838c0b567aacbb6f638cf",
        UINT64_C(16756736),
        GDOX_XENIA_GPU_D3D12,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
#elif defined(GDOX_XENIA_CATALOG_LINUX)
        "xenia_canary.exe",
        "cd0a9c6bddf0d0b960cb24f63efa5d56ecd34fdf20a838c0b567aacbb6f638cf",
        UINT64_C(16756736),
        GDOX_XENIA_GPU_D3D12,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
#else
        "",
        "",
        UINT64_C(0),
        GDOX_XENIA_GPU_D3D12,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
#endif
    },
};

static const gdox_xenia_launch_policy default_policy =
    {
        &runtimes[0],
        "default.xex",
        GDOX_XENIA_PATCH_SET_NONE,
        {
            .allow_tearing = false,
            .vsync = true,
            .max_queued_frames = 64U,
            .allow_invalid_fetch_constants = false,
            .occlusion_query = GDOX_XENIA_OCCLUSION_DEFAULT,
            .occlusion_query_saturation_basis_points = 10000U,
            .readback_resolve = GDOX_XENIA_READBACK_NONE,
            .protect_zero = true,
            .new_xma_decoder = true,
            .use_dedicated_xma_thread = true,
            .async_shader_compilation = true,
            .use_handheld_custom_resolution = true,
        },
    };

static const gdox_xenia_title_policy_entry title_policies[] = {
    {
        {UINT32_C(0x4d5307dc), UINT32_C(0x596f9615), 1U, 1U},
        {
            &runtimes[0],
            "default.xex",
            GDOX_XENIA_PATCH_SET_NONE,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = false,
                .occlusion_query = GDOX_XENIA_OCCLUSION_FAST_ALT,
                .occlusion_query_saturation_basis_points = 10000U,
                .readback_resolve = GDOX_XENIA_READBACK_FULL,
                .protect_zero = false,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = false,
                .async_shader_compilation = true,
                .use_handheld_custom_resolution = true,
            },
        },
    },
    {
        {UINT32_C(0x4d5307e6), UINT32_C(0x699e0227), 1U, 1U},
        {
            &runtimes[0],
            "default.xex",
            GDOX_XENIA_PATCH_SET_NONE,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = false,
                .occlusion_query = GDOX_XENIA_OCCLUSION_DEFAULT,
                .occlusion_query_saturation_basis_points = 10000U,
                .readback_resolve = GDOX_XENIA_READBACK_FAST,
                .protect_zero = false,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = true,
                .async_shader_compilation = true,
                .use_handheld_custom_resolution = true,
            },
        },
    },
    {
        {UINT32_C(0x4d5307e8), UINT32_C(0x572ba75d), 1U, 1U},
        {
            &runtimes[0],
            "default.xex",
            GDOX_XENIA_PATCH_SET_MASS_EFFECT_WORLD_RENDERING_V1,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = false,
                .occlusion_query = GDOX_XENIA_OCCLUSION_STRICT,
                .occlusion_query_saturation_basis_points = 7500U,
                .readback_resolve = GDOX_XENIA_READBACK_NONE,
                .protect_zero = true,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = true,
                .async_shader_compilation = false,
                .use_handheld_custom_resolution = false,
            },
        },
    },
    {
        {UINT32_C(0x4d530919), UINT32_C(0x1c9d20bc), 1U, 1U},
        {
            &runtimes[1],
            "default.xex",
            GDOX_XENIA_PATCH_SET_NONE,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = false,
                .occlusion_query = GDOX_XENIA_OCCLUSION_DEFAULT,
                .occlusion_query_saturation_basis_points = 10000U,
                .readback_resolve = GDOX_XENIA_READBACK_FAST,
                .protect_zero = true,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = true,
                .async_shader_compilation = true,
                .use_handheld_custom_resolution = true,
            },
        },
    },
    {
        {UINT32_C(0x555308ae), UINT32_C(0x6d9f552e), 1U, 2U},
        {
            &runtimes[1],
            "scimitar_final.xex",
            GDOX_XENIA_PATCH_SET_NONE,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = true,
                .occlusion_query = GDOX_XENIA_OCCLUSION_STRICT,
                .occlusion_query_saturation_basis_points = 10000U,
                .readback_resolve = GDOX_XENIA_READBACK_NONE,
                .protect_zero = true,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = true,
                .async_shader_compilation = true,
                .use_handheld_custom_resolution = true,
            },
        },
    },
    {
        {UINT32_C(0x555308c2), UINT32_C(0x68ec85bf), 1U, 2U},
        {
            &runtimes[0],
            "scimitar_final.xex",
            GDOX_XENIA_PATCH_SET_NONE,
            {
                .allow_tearing = false,
                .vsync = true,
                .max_queued_frames = 64U,
                .allow_invalid_fetch_constants = true,
                .occlusion_query = GDOX_XENIA_OCCLUSION_STRICT,
                .occlusion_query_saturation_basis_points = 10000U,
                .readback_resolve = GDOX_XENIA_READBACK_FULL,
                .protect_zero = true,
                .new_xma_decoder = true,
                .use_dedicated_xma_thread = true,
                .async_shader_compilation = true,
                .use_handheld_custom_resolution = true,
            },
        },
    },
};

const gdox_xenia_launch_policy *gdox_xenia_default_policy(void)
{
    return &default_policy;
}

const gdox_xenia_launch_policy *gdox_xenia_select_policy(
    const gdox_xenia_title_identity *identity
)
{
    size_t index;

    if (identity == NULL) {
        return &default_policy;
    }
    for (index = 0U;
         index < sizeof(title_policies) / sizeof(title_policies[0]);
         ++index) {
        const gdox_xenia_title_identity *candidate =
            &title_policies[index].identity;
        if (candidate->title_id == identity->title_id
            && candidate->media_id == identity->media_id
            && candidate->disc_number == identity->disc_number
            && candidate->disc_count == identity->disc_count) {
            return &title_policies[index].policy;
        }
    }
    return &default_policy;
}

size_t gdox_xenia_runtime_count(void)
{
    return sizeof(runtimes) / sizeof(runtimes[0]);
}

const gdox_xenia_runtime *gdox_xenia_runtime_at(size_t index)
{
    if (index >= gdox_xenia_runtime_count()) {
        return NULL;
    }
    return &runtimes[index];
}

const gdox_xenia_runtime *gdox_xenia_runtime_by_revision(
    const char *revision
)
{
    size_t index;

    if (revision == NULL || revision[0] == '\0') {
        return NULL;
    }
    for (index = 0U; index < gdox_xenia_runtime_count(); ++index) {
        if (strcmp(runtimes[index].revision, revision) == 0) {
            return &runtimes[index];
        }
    }
    return NULL;
}
